import 'package:proyecto/models/residence.dart';

final List<Residence> residences = [
    Residence(
      residenceID: 1,
      companyID: 101,
      title: 'Desarrollo de Software en StartupTech',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Internado en desarrollo de software en una startup tecnológica. Oportunidad de aprender sobre desarrollo web y móvil.',
      address: 'Avenida Innovación #456',
      publishedDate: DateTime(2024, 4, 15),
    ),
    Residence(
      residenceID: 2,
      companyID: 102,
      title: 'Marketing Digital en Agencia Creativa',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Prácticas en marketing digital en una agencia creativa. Trabaja en proyectos reales de clientes y aprende sobre estrategias de marketing online.',
      address: 'Calle Creatividad #789',
      publishedDate: DateTime(2024, 4, 18),
    ),
    Residence(
      residenceID: 3,
      companyID: 103,
      title: 'Diseño Gráfico en Estudio de Diseño Gráfico',
      InitialDate: DateTime(2024, 6, 15),
      FinalDate: DateTime(2024, 9, 15),
      description: 'Internado en diseño gráfico en un estudio de diseño reconocido. Crea contenido visual para marcas y campañas publicitarias.',
      address: 'Plaza Arte #321',
      publishedDate: DateTime(2024, 4, 20),
    ),
    Residence(
      residenceID: 4,
      companyID: 104,
      title: 'Ingeniería Civil en Empresa de Construcción',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Prácticas en ingeniería civil en una empresa constructora. Participa en proyectos de infraestructura y aprende sobre diseño y construcción.',
      address: 'Avenida Obras #567',
      publishedDate: DateTime(2024, 4, 22),
    ),
    Residence(
      residenceID: 5,
      companyID: 105,
      title: 'Recursos Humanos en Corporación Global',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Internado en el departamento de recursos humanos en una corporación global. Participa en procesos de reclutamiento, selección y formación de personal.',
      address: 'Torre Corporativa #101',
      publishedDate: DateTime(2024, 4, 25),
    ),
    Residence(
      residenceID: 6,
      companyID: 106,
      title: 'Desarrollo Web en Agencia de Marketing Digital',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Prácticas en desarrollo web en una agencia de marketing digital. Trabaja en la creación y mantenimiento de sitios web para clientes.',
      address: 'Calle Digital #246',
      publishedDate: DateTime(2024, 4, 28),
    ),
    Residence(
      residenceID: 7,
      companyID: 107,
      title: 'Investigación en Laboratorio Científico',
      InitialDate: DateTime(2024, 7, 15),
      FinalDate: DateTime(2024, 10, 15),
      description: 'Internado en investigación científica en un laboratorio especializado. Contribuye a proyectos de investigación y experimentación en diversas áreas.',
      address: 'Avenida Ciencia #789',
      publishedDate: DateTime(2024, 5, 1),
    ),
    Residence(
      residenceID: 8,
      companyID: 108,
      title: 'Contabilidad en Firma de Contadores',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Prácticas en contabilidad en una firma de contadores. Aprende sobre auditorías, declaraciones fiscales y análisis financiero.',
      address: 'Calle Finanzas #333',
      publishedDate: DateTime(2024, 5, 4),
    ),
    Residence(
      residenceID: 9,
      companyID: 109,
      title: 'Arquitectura en Estudio de Arquitectura',
      InitialDate: DateTime(2024, 6, 15),
      FinalDate: DateTime(2024, 9, 15),
      description: 'Internado en arquitectura en un estudio reconocido. Participa en el diseño y planificación de proyectos arquitectónicos innovadores.',
      address: 'Paseo Arquitectura #999',
      publishedDate: DateTime(2024, 5, 7),
    ),
    Residence(
      residenceID: 10,
      companyID: 110,
      title: 'Periodismo en Medio de Comunicación',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Prácticas en periodismo en un medio de comunicación local. Cubre noticias, entrevistas y redacta artículos para su publicación.',
      address: 'Plaza Noticias #777',
      publishedDate: DateTime(2024, 5, 10),
    ),
    Residence(
      residenceID: 11,
      companyID: 111,
      title: 'Psicología en Clínica de Salud Mental',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Internado en psicología en una clínica de salud mental. Participa en terapias, evaluaciones psicológicas y programas de intervención.',
      address: 'Avenida Salud #222',
      publishedDate: DateTime(2024, 5, 13),
    ),
    Residence(
      residenceID: 12,
      companyID: 112,
      title: 'Educación en Escuela Primaria',
      InitialDate: DateTime(2024, 6, 15),
      FinalDate: DateTime(2024, 9, 15),
      description: 'Prácticas en educación en una escuela primaria. Asiste a clases, prepara materiales didácticos y colabora con el personal docente.',
      address: 'Calle Educación #888',
      publishedDate: DateTime(2024, 5, 16),
    ),
    Residence(
      residenceID: 13,
      companyID: 113,
      title: 'Biología en Instituto de Investigación',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Internado en biología en un instituto de investigación. Realiza experimentos, analiza muestras y contribuye al avance científico.',
      address: 'Avenida Biología #555',
      publishedDate: DateTime(2024, 5, 19),
    ),
    Residence(
      residenceID: 14,
      companyID: 114,
      title: 'Ingeniería Eléctrica en Empresa de Energía',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Prácticas en ingeniería eléctrica en una empresa de energía. Participa en proyectos de generación, distribución y control de energía eléctrica.',
      address: 'Calle Energía #444',
      publishedDate: DateTime(2024, 5, 22),
    ),
    Residence(
      residenceID: 15,
      companyID: 115,
      title: 'Medicina en Hospital General',
      InitialDate: DateTime(2024, 6, 15),
      FinalDate: DateTime(2024, 9, 15),
      description: 'Internado en medicina en un hospital general. Observa procedimientos médicos, asiste a consultas y aprende sobre diagnóstico y tratamiento.',
      address: 'Avenida Salud #333',
      publishedDate: DateTime(2024, 5, 25),
    ),
    Residence(
      residenceID: 16,
      companyID: 116,
      title: 'Finanzas en Banco Nacional',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Prácticas en finanzas en un banco nacional. Aprende sobre servicios financieros, gestión de riesgos y análisis de inversiones.',
      address: 'Paseo Finanzas #222',
      publishedDate: DateTime(2024, 5, 28),
    ),
    Residence(
      residenceID: 17,
      companyID: 117,
      title: 'Química en Laboratorio Farmacéutico',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Internado en química en un laboratorio farmacéutico. Realiza análisis químicos, investiga nuevos compuestos y contribuye al desarrollo de medicamentos.',
      address: 'Avenida Química #777',
      publishedDate: DateTime(2024, 6, 1),
    ),
    Residence(
      residenceID: 18,
      companyID: 118,
      title: 'Gestión Ambiental en Organización Ambiental',
      InitialDate: DateTime(2024, 6, 15),
      FinalDate: DateTime(2024, 9, 15),
      description: 'Prácticas en gestión ambiental en una organización dedicada a la conservación del medio ambiente. Participa en proyectos de sostenibilidad y conservación de recursos naturales.',
      address: 'Calle Ambiente #999',
      publishedDate: DateTime(2024, 6, 4),
    ),
    Residence(
      residenceID: 19,
      companyID: 119,
      title: 'Derecho en Despacho de Abogados',
      InitialDate: DateTime(2024, 7, 1),
      FinalDate: DateTime(2024, 9, 30),
      description: 'Internado en derecho en un despacho de abogados. Asiste a juicios, investiga casos legales y redacta documentos legales.',
      address: 'Plaza Legal #666',
      publishedDate: DateTime(2024, 6, 7),
    ),
    Residence(
      residenceID: 20,
      companyID: 120,
      title: 'Ingeniería Mecánica en Empresa Automotriz',
      InitialDate: DateTime(2024, 6, 1),
      FinalDate: DateTime(2024, 8, 31),
      description: 'Prácticas en ingeniería mecánica en una empresa automotriz. Participa en el diseño, desarrollo y prueba de componentes mecánicos para vehículos.',
      address: 'Calle Mecánica #111',
      publishedDate: DateTime(2024, 6, 10),
    ),
  ];